# -*- coding: utf-8 -*-
"""colab_server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGzol_xJ_jHF83LNMwWHXH2RT0X8kI5j

## Dependencias + Montar Drive
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install "torch==2.2.0" --index-url https://download.pytorch.org/whl/cpu -q
# !pip install "stable-baselines3>=2.4.0" \
#              "gymnasium==1.2.0" \
#              "shimmy>=2.0.0" \
#              "shap>=0.46.0" \
#              "scikit-learn" \
#              "fastapi" \
#              "uvicorn" \
#              "pyngrok" \
#              "pandas" \
#              "matplotlib" \
#              --no-cache-dir -q

import numpy as np
import torch
import shap
import stable_baselines3 as sb3
from stable_baselines3 import SAC
import sklearn, gymnasium

print(f"numpy:     {np.__version__}")        # 2.x   ✅
print(f"torch:     {torch.__version__}")     # 2.2.0 ✅
print(f"shap:      {shap.__version__}")      # 0.46+ ✅
print(f"sb3:       {sb3.__version__}")        # 2.4+  ✅
print(f"gymnasium: {gymnasium.__version__}") # 1.2.0 ✅
print(f"sklearn:   {sklearn.__version__}")   # ✅

print("\n🚀 Entorno listo para LSTM + SAC + SHAP")

from google.colab import drive
# Añadimos force_remount=True para asegurar que intente una conexión limpia si falló antes
drive.mount('/content/drive')

import sys
DRIVE_ROOT = '/content/drive/MyDrive/TFM-NeuroQuant'

MODELS_PATH = f'{DRIVE_ROOT}/models'
print("Drive montado correctamente")

"""## Definición modelo

"""

import torch
import torch.nn as nn

class LSTMModel(nn.Module):
    def __init__(self, input_size=20, hidden_size=256, num_layers=2,
                 output_size=4, dropout=0.2,
                 mlp_hidden=64, head_hidden=32):
        super().__init__()

        self.input_proj = nn.Sequential(
            nn.Linear(input_size, hidden_size),   # input_proj.0
            nn.LayerNorm(hidden_size)             # input_proj.1
        )

        self.lstm = nn.LSTM(
            input_size  = hidden_size,
            hidden_size = hidden_size,
            num_layers  = num_layers,
            batch_first = True,
            dropout     = dropout if num_layers > 1 else 0.0
        )

        self.attn = nn.Linear(hidden_size, 1)
        self.norm = nn.LayerNorm(hidden_size)

        # MLP: hidden_size → mlp_hidden → head_hidden
        self.mlp = nn.Sequential(
            nn.Linear(hidden_size, mlp_hidden),   # mlp.0
            nn.LayerNorm(mlp_hidden),             # mlp.1
            nn.ReLU(),                            # mlp.2 (sin parámetros)
            nn.Dropout(dropout),                  # mlp.3 (sin parámetros)
            nn.Linear(mlp_hidden, head_hidden),   # mlp.4
        )

        self.head = nn.Linear(head_hidden, output_size)

    def forward(self, x):
        x       = self.input_proj(x)
        out, _  = self.lstm(x)
        attn_w  = torch.softmax(self.attn(out), dim=1)
        context = (attn_w * out).sum(dim=1)
        context = self.norm(context)
        context = self.mlp(context)
        return self.head(context)   # → (batch, 4)

COIN_CONFIGS = {
    "BTC":  {"hidden_size": 256, "num_layers": 2, "mlp_hidden": 64,  "head_hidden": 32, "seq_len": 24},
    "ETH":  {"hidden_size": 64,  "num_layers": 3, "mlp_hidden": 64,  "head_hidden": 32, "seq_len": 24},
    "SOL":  {"hidden_size": 256, "num_layers": 2, "mlp_hidden": 64,  "head_hidden": 32, "seq_len": 24},
    "AVAX": {"hidden_size": 128, "num_layers": 2, "mlp_hidden": 32,  "head_hidden": 16, "seq_len": 24},
}

print("✅ LSTMModel definido con arquitectura correcta")

"""## Llamada API"""

import torch
import numpy as np
import shap
import time
import json
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from stable_baselines3 import SAC

api = FastAPI(title="NeuroQuant Inference API")

# ── Carga de modelos (una vez) ────────────────────────────────────────────────
COINS   = ['BTC', 'ETH', 'SOL', 'AVAX']
DEVICE  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
MODELS  = {}

SHAP_ENABLED = True

FEATURE_NAMES = [
    'close','volume','return_1','return_7','rsi_14','macd',
    'macd_signal','bb_position','bb_width','atr_14','volume_ratio',
    'hour_sin','hour_cos','dow_sin','dow_cos','fear_greed',
    'return_4h','rsi_4h','return_1d','rsi_1d'
]

print(f"📦 Cargando modelos en {DEVICE}...")
for coin, cfg in COIN_CONFIGS.items():
    # LSTM
    lstm = LSTMModel(
        input_size   = 20,
        hidden_size  = cfg["hidden_size"],
        num_layers   = cfg["num_layers"],
        mlp_hidden   = cfg["mlp_hidden"],
        head_hidden  = cfg["head_hidden"],
        output_size  = 4,
    )
    state_dict = torch.load(
        f'{MODELS_PATH}/lstm/best_{coin}.pt',
        map_location=DEVICE, weights_only=True
    )
    lstm.load_state_dict(state_dict)
    lstm.eval().to(DEVICE)
    MODELS[f'{coin}_LSTM'] = lstm
    print(f"  ✅ {coin} LSTM — hidden={cfg['hidden_size']}, layers={cfg['num_layers']}, mlp={cfg['mlp_hidden']}, head={cfg['head_hidden']}")

    # SAC
    sac = SAC.load(
        f'{MODELS_PATH}/sac/sac_{coin}_best.zip',
        device=DEVICE
    )
    MODELS[f'{coin}_SAC'] = sac
    print(f"  ✅ {coin} SAC cargado")

print(f"\n🚀 Modelos listos: {list(MODELS.keys())}")

import joblib
scalers = {}
reg_scalers = {}
for coin in COINS:
    pkl = joblib.load(f'{MODELS_PATH}/lstm/scaler_{coin}.pkl')
    scalers[coin]     = pkl['feat_scaler']
    reg_scalers[coin] = pkl['reg_scaler']

sac_means = {}
sac_stds   = {}
for coin in COINS:
  sac_means[coin] = np.load(f'{MODELS_PATH}/sac/sac_feat_mean_{coin}.npy')
  sac_stds[coin]   = np.load(f'{MODELS_PATH}/sac/sac_feat_std_{coin}.npy')
  print(f" {coin} SAC stats -> mean: {sac_means[coin].shape}")

# ── Schemas ───────────────────────────────────────────────────────────────────
class PredictRequest(BaseModel):
    symbol:  str
    X_input: list     # (seq_len, features) como lista Python
    current_price: float = None

WF_DIRACC = {
    'BTC':  {'H1': 0.569, 'H2': 0.596, 'H3': 0.610, 'H4': 0.620},
    'ETH':  {'H1': 0.574, 'H2': 0.607, 'H3': 0.619, 'H4': 0.629},
    'SOL':  {'H1': 0.542, 'H2': 0.572, 'H3': 0.585, 'H4': 0.600},
    'AVAX': {'H1': 0.518, 'H2': 0.553, 'H3': 0.566, 'H4': 0.591},
}

# ── Endpoint principal ────────────────────────────────────────────────────────
@api.post("/predict")
def predict(req: PredictRequest):
  try:
      symbol = req.symbol.upper()
      if f'{symbol}_LSTM' not in MODELS:
          raise HTTPException(404, f"Modelo {symbol} no disponible")

      t0     = time.perf_counter()
      X      = np.array(req.X_input, dtype=np.float32)   # (24, 20) raw
      X_norm = scalers[symbol].transform(X)               # (24, 20) escalado

      lstm_model = MODELS[f'{symbol}_LSTM']
      sac_model  = MODELS[f'{symbol}_SAC']

      # ── Precio base ───────────────────────────────────────────────────
      # Usar precio live del cliente si llega, si no el último close de X
      current_price = float(req.current_price) if req.current_price \
                      else float(X[-1, 0])

      # ── LSTM — predicción principal ───────────────────────────────────
      tensor = torch.FloatTensor(X_norm).unsqueeze(0).to(DEVICE)
      with torch.no_grad():
          preds_norm = lstm_model(tensor)[0].tolist()   # 4 retornos normalizados

      preds_real = reg_scalers[symbol].inverse_transform(
          np.array(preds_norm).reshape(1, -1)
      ).flatten().tolist()

      price_1h = round(current_price * (1 + preds_real[0]), 2)
      price_2h = round(current_price * (1 + preds_real[1]), 2)
      price_3h = round(current_price * (1 + preds_real[2]), 2)
      price_4h = round(current_price * (1 + preds_real[3]), 2)

      # ── Monte Carlo Dropout ───────────────────────────────────────────
      scale_1h  = float(reg_scalers[symbol].scale_[0])
      center_1h = float(reg_scalers[symbol].center_[0])

      lstm_model.train()
      mc_preds = []
      with torch.no_grad():
          for _ in range(50):
              mc_preds.append(lstm_model(tensor)[0][0].item())
      lstm_model.eval()

      mc_min_ret = float(np.percentile(mc_preds,  5)) * scale_1h + center_1h
      mc_max_ret = float(np.percentile(mc_preds, 95)) * scale_1h + center_1h
      price_min  = round(current_price * (1 + mc_min_ret), 2)
      price_max  = round(current_price * (1 + mc_max_ret), 2)

      # ── SAC — decisión ────────────────────────────────────────────────
      X_sac_norm = np.clip(
          (X - sac_means[symbol]) / sac_stds[symbol],
          -5.0, 5.0
      ).astype(np.float32)

      state_rl       = np.zeros(643, dtype=np.float32)
      state_rl[160:640] = X_sac_norm.flatten()
      state_rl[640]  = 0.0   # position: sin posición abierta
      state_rl[641]  = 0.0   # PnL: neutro
      state_rl[642]  = 1.0   # capital: completo disponible
      # ⚠ slots 480:640 quedan en 0 hasta tener feat_mean/feat_std nuevos

      action, _  = sac_model.predict(state_rl, deterministic=True)
      raw_action = float(action)
      abs_action = abs(raw_action)

      if raw_action < -0.33:
          sac_decision = "VENDER"
          probs = [round(0.33 + abs_action * 0.34, 2), 0.33,
                   round(0.34 - abs_action * 0.34, 2)]
      elif raw_action > 0.33:
          sac_decision = "COMPRAR"
          probs = [round(0.34 - abs_action * 0.34, 2), 0.33,
                   round(0.33 + abs_action * 0.34, 2)]
      else:
          sac_decision = "MANTENER"
          probs = [round(0.33 - abs_action * 0.1, 2),
                   round(0.34 + abs_action * 0.2, 2),
                   round(0.33 - abs_action * 0.1, 2)]

      # ── Árbitro LSTM vs SAC — señal primaria: H4 ─────────────────────
      MIN_CONFIDENCE = 0.45   # umbral mínimo para operar

      lstm_direction = 1 if preds_real[3] > 0 else -1
      sac_direction  = (1 if raw_action > 0.33
                  else (-1 if raw_action < -0.33 else 0))

      if lstm_direction == sac_direction:
        final_decision   = sac_decision
        final_confidence = round(max(probs), 4)
        signal_agreement = True

      elif sac_direction == 0:

        final_confidence = round(abs(preds_real[3]) * 100, 4)
        if final_confidence >= MIN_CONFIDENCE:
          final_decision   = "COMPRAR" if lstm_direction > 0 else "VENDER"
          signal_agreement = True
        else:
          final_decision   = "MANTENER"
          signal_agreement = True   # no es contradicción, es señal débil
          probs            = [0.33, 0.34, 0.33]

      else:
        final_decision   = "MANTENER"
        final_confidence = 0.33
        probs            = [0.33, 0.34, 0.33]
        signal_agreement = False


      # ── Métricas sobre precios reales ─────────────────────────────────
      prices = X[:, 0]
      actual_returns = np.diff(prices) / (prices[:-1] + 1e-8)   # (23,)

      preds_hist = []
      with torch.no_grad():
          for i in range(4, len(prices)):
              t_slice = torch.FloatTensor(
                  X_norm[i-4:i]).unsqueeze(0).to(DEVICE)
              pred_n  = lstm_model(t_slice)[0][0].item()
              preds_hist.append(pred_n * scale_1h + center_1h)

      actual_h = actual_returns[3:]
      ph       = np.array(preds_hist)

      prices_base   = prices[3:23]
      prices_actual = prices[4:24]
      prices_pred   = prices_base * (1 + ph)

      rmse   = float(np.sqrt(np.mean((prices_actual - prices_pred) ** 2)))
      mae    = float(np.mean(np.abs(prices_actual - prices_pred)))
      mape   = float(np.mean(
          np.abs((prices_actual - prices_pred) / prices_actual)) * 100)
      rets   = np.diff(ph) / (np.abs(ph[:-1]) + 1e-8)
      sharpe = float((rets.mean() / (rets.std() + 1e-8)) * np.sqrt(252))

      pred_dirs   = np.sign(ph)
      actual_dirs = np.sign(actual_h)
      window_diracc = float(np.mean(pred_dirs == actual_dirs))

      # ── SHAP ──────────────────────────────────────────────────────────
      base_seq = X_norm.copy()
      def lstm_predict_flat(x_flat):
          results = []
          for row in x_flat:
              seq = base_seq.copy()
              seq[-1] = row
              t = torch.FloatTensor(seq).unsqueeze(0).to(DEVICE)
              with torch.no_grad():
                  results.append(lstm_model(t)[0][0].item())
          return np.array(results)

      background = X_norm[-5:]
      explainer  = shap.KernelExplainer(lstm_predict_flat, background)
      shap_vals  = explainer.shap_values(
          X_norm[-1:], nsamples=100, silent=True)

      latency = round((time.perf_counter() - t0) * 1000, 1)

      return {
          "symbol": symbol,
          "lstm": {
              "predicted_price": price_1h,
              "1h":              price_1h,
              "2h":              price_2h,
              "3h":              price_3h,
              "4h":              price_4h,
              "min":             price_min,
              "max":             price_max,
          },
          "rl": {
              "decision":         final_decision,
              "action_probs":     probs,
              "confidence":       final_confidence,
              "raw_action":       round(raw_action, 4),
              "signal_agreement": signal_agreement,
          },
          "metrics": {
              "rmse":          round(rmse,   2),
              "mae":           round(mae,    2),
              "mape":          round(mape,   4),
              "sharpe_window": round(sharpe, 4),
              "window_diracc": round(window_diracc, 4),
          },
          "direction_accuracy": WF_DIRACC.get(symbol, {}),
          "shap": {
              "feature_names": FEATURE_NAMES,
              "values":        shap_vals[0].tolist(),
              "base_value":    float(explainer.expected_value),
          },
          "latency_ms": latency,
      }

  except Exception as e:
      import traceback
      raise HTTPException(status_code=500, detail=traceback.format_exc())

# ── Health check

@api.get("/health")
def health():
    return {"status": "ok", "models": list(MODELS.keys())}

"""## Lanzar servidor + ngrok"""

import threading
import uvicorn
from pyngrok import ngrok, conf

# ── Tu authtoken de ngrok.com (gratis) ───────────────────────────────────────
NGROK_TOKEN = "3DVBDJ4Zkd3MkEGBIKxWOgOpu0o_2H5BBP6qf4mT2YaPhQy2q"
ngrok.set_auth_token(NGROK_TOKEN)

# ── Lanzar uvicorn en thread background ──────────────────────────────────────
def run_server():
    uvicorn.run(api, host="0.0.0.0", port=8000, log_level="warning")

thread = threading.Thread(target=run_server, daemon=True)
thread.start()
time.sleep(2)   # espera a que arranque

# ── Abrir túnel ngrok ─────────────────────────────────────────────────────────
tunnel    = ngrok.connect(8000, "http")
public_url = tunnel.public_url

print(f"\n{'='*50}")
print(f"🌐 URL pública:  {public_url}")
print(f"🔍 Health check: {public_url}/health")
print(f"📡 Endpoint:     {public_url}/predict")
print(f"{'='*50}")

# ── Guardar URL para que el cliente local la lea automáticamente ──────────────
import json
from google.colab import files

url_config = {"cloud_url": f"{public_url}/predict"}
with open("ngrok_url.json", "w") as f:
    json.dump(url_config, f)

# files.download("ngrok_url.json")   # descarga automática al PC